apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetapp-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aspnetapp-k8s
  template:
    metadata:
      labels:
        app: aspnetapp-k8s
    spec:
      containers:
      - name: aspnetapp-k8s
        image: aspnetapp-k8s
        imagePullPolicy: Never
        ports:
          - containerPort: 4999
            name: http-port
          - containerPort: 5000
            name: http2-port
          - containerPort: 5001
            name: http3-port
   